backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} {{slug}}'
    update: 'Update {{collection}} {{slug}}'
    delete: 'Delete {{collection}}{{slug}}'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "path", widget: "hidden", default: "{{slug}}"
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }