backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}'
    update: 'Update {{collection}}'
    delete: 'Delete {{collection}}'

media_folder: "static/uploads"
public_folder: "uploads"