backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} {{slug}}'
    update: 'Update {{collection}} {{slug}}'
    delete: 'Delete {{collection}}{{slug}}'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Blog"
    name: "blog"
    identifier_field: "blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "path", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }
  - label: "Landing-Page"
    name: "landing"
    identifier_field: "landing"
    files:
      - label: "Head"
        name: "head"
        identifier_field: "head"
        file: "src/pages/landing/landing.md"
        fields:
          - { label: "Intro Slogan", name: "intro", widget: "string"}
          - { label: "Mid Slogan", name: "mid", widget: "string"}
          - { label: "Outro Slogan", name: "outro", widget: "string"}
      - label: "HowWeWork"
        name: "howWeWork"
        identifier_field: "howWeWork"
        file: "src/pages/landing/landing.md"
        fields:
          - { label: "Section Title", name: "title", widget: "string"}
          - label: "First Feature",
            name: "first-Feature",
            widget: "object"
            fields: {
              - { label: "Feature Title", name: "firstFeatureTitle", widget: "string"}
              - { label: "Feature Description", name: "firstFeatureDescription", widget: "string"}
            }
          - label: "Second Feature",
            name: "second-Feature",
            widget: "object"
            fields: {
              - { label: "Feature Title", name: "secondFeatureTitle", widget: "string"}
              - { label: "Feature Description", name: "secondFeatureDescription", widget: "string"}
            }
          - label: "Third Feature",
            name: "third-Feature",
            widget: "object"
            fields: {
              - { label: "Feature Title", name: "thirdFeatureTitle", widget: "string"}
              - { label: "Feature Description", name: "thirdFeatureDescription", widget: "string"}
            }