backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} {{slug}}'
    update: 'Update {{collection}} {{slug}}'
    delete: 'Delete {{collection}}{{slug}}'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "path", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }
  - label: "Landing-Page"
    name: "landing"
    files:
      - label: "Slogan"
        name: "slogan"
        file: "src/pages/landing.yml"
        fields:
          - { label: "Intro-slogan", name: "intro", widget: "string", default: "Crea y distribuye"}
          - { label: "Mid-slogan", name: "mid", widget: "string", default: "Comunicados de prensa"}
          - { label: "Outro-slogan", name: "outro", widget: "string", default: "De una manera más fácil, rápida y sencilla."}