backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}'
    update: 'Update {{collection}}'
    delete: 'Delete {{collection}}'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/pages/blog"
    create: true
    preview_path: "blog/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "{{preview_path}}"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }