backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}'
    update: 'Update {{collection}}'
    delete: 'Delete {{collection}}'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    preview_path: "blog/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "hidden", collection: "blog", searchFields: "preview_path", valueField: "preview_path"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }