backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create in {{collection}} {{slug}} post'
    update: 'Update in {{collection}} {{slug}} post'
    delete: 'Delete in {{collection}} {{slug}} post'

media_folder: static/img
public_folder: /img

collections:
  - label: "Blog Contenido"
    name: "blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
    - { label: "Titulo del post", name: "title", widget: "string" }
    - { label: "Fecha de publicación", name: "date", widget: "datetime" }
    - { label: "Descripción del post", name: "description", widget: "string" }
    - label: "Imagen del post"
      name: "postImage"
      required: false
      widget: "image"
      media_library:
        config:
          multiple: false
    - { label: "Contenido del post", name: "body", widget: "markdown" }
    - { label: "Autor del post", name: "author", widget: "string" }
  - label: "Landing Contenido"
    name: "landing"
    identifier_field: "landing"
    files:
    - label: "Sección Head del sitio"
      name: "head"
      identifier_field: "head"
      file: "content/landing/head.md"
      fields:
      - { label: "Frase de introducción en header", name: "intro", widget: "string"}
      - { label: "Frase en medio del header", name: "mid", widget: "string"}
      - { label: "Frase final en header", name: "outro", widget: "string"}
    - label: "Sección como trabajamos"
      name: "howWeWork"
      identifier_field: "howWeWork"
      file: "content/landing/howWeWork.md"
      fields:
      - { label: "Titulo de la sección", name: "sectionTitle", widget: "string"}
      - {
        label: "Contenido del primer Feature",
        name: "firstFeature",
        widget: "object",
        fields:
          [
          { label: "Titulo del Feature", name: "firstFeatureTitle", widget: "string"},
          { label: "Descripción del Feature", name: "firstFeatureDescription", widget: "string"}
          ]
        }
      - {
        label: "Contenido del segundo Feature",
        name: "secondFeature",
        widget: "object",
        fields:
          [
          { label: "Titulo del Feature", name: "secondFeatureTitle", widget: "string"},
          { label: "Descripción del Feature", name: "secondFeatureDescription", widget: "string"}
          ]
        }
      - {
        label: "Contenido del tercer Feature",
        name: "thirdFeature",
        widget: "object",
        fields:
          [
          { label: "Titulo del Feature", name: "thirdFeatureTitle", widget: "string"},
          { label: "Descripción del Feature", name: "thirdFeatureDescription", widget: "string"}
          ]
        }
    - label: "Sección del Footer"
      name: "footer"
      identifier_field: "footer"
      file: "content/landing/footer.md"
      fields:
      - {
        label: "Contenido superior de la sección",
        name: "topSection",
        widget: "object",
        fields:
          [
          { label: "Titulo del contenido superior", name: "topSectionTitle", widget: "string"},
          { label: "Frase del contenido superior", name: "topSectionSlogan", widget: "string"}
          ]
      }
      - {
        label: "Contenido inferior de la sección",
        name: "bottomSection",
        widget: "object",
        fields:
          [
          { label: "Titulo del contenido inferior", name: "bottomSectionTitle", widget: "string"},
          { label: "Frase del contenido inferior", name: "bottomSectionSlogan", widget: "string"}
          ]
      }
    - label: "Sección de contacto"
      name: "greetings"
      identifier_field: "greetings"
      file: "content/landing/greetings.md"
      fields:
      - { label: "Saludos", name: "sectionGreetings", widget: "string"}
      - { label: "Mensaje y contacto", name: "sectionMessage", widget: "string"}
    - label: "Redes sociales"
      name: "social"
      identifier_field: "social"
      file: "content/landing/social.md"
      fields:
      - { label: "Facebook", name: "socialFacebook", required: false, widget: "string"}
      - { label: "Instagram", name: "socialInstagram", required: false, widget: "string"}
      - { label: "Whatsapp", name: "socialWhatsapp", required: false, widget: "string"}
  - label: "Paquetes y precios"
      name: "packages"
      identifier_field: "packages"
      file: "content/packages/packagesData.md"
      fields:
        - label: "Primer paquete"
          name: "firstPackage"
          identifier_field: "firstPackage"
          widget: "object"
          fields:
            [
            { label: "Título del paquete", name: "firstPackageTitle", widget: "string"},
            { label: "Precio del paquete", name: "firstPackagePrice", widget: "string"},
            { label: "Beneficios del paquete",
              name: "firstPackageBenefits",
              widget: "object",
              fields:
                [
                { label: "Primer beneficio", label: "firstPackFirstBenefit", widget: "string"},
                { label: "Segundo beneficio", label: "firstPackSecondBenefit", required: false, widget: "string"},
                { label: "Tercer beneficio", label: "firstPackThirdBenefit", required: false, widget: "string"},
                { label: "Cuarto beneficio", label: "firstPackFourthBenefit", required: false, widget: "string"},
                { label: "Quinto beneficio", label: "firstPackFifthBenefit", required: false, widget: "string"}
                ]
            }
            ]
        - label: "Segundo paquete"
          name: "secondPackage"
          identifier_field: "secondPackage"
          widget: "object"
          fields:
            [
            { label: "Título del paquete", name: "secondPackageTitle", widget: "string"},
            { label: "Precio del paquete", name: "secondPackagePrice", widget: "string"},
            { label: "Beneficios del paquete",
              name: "secondPackageBenefits",
              widget: "object",
              fields:
                [
                { label: "Primer beneficio", label: "secondPackFirstBenefit", widget: "string"},
                { label: "Segundo beneficio", label: "secondPackSecondBenefit", required: false, widget: "string"},
                { label: "Tercer beneficio", label: "secondPackThirdBenefit", required: false, widget: "string"},
                { label: "Cuarto beneficio", label: "secondPackFourthBenefit", required: false, widget: "string"},
                { label: "Quinto beneficio", label: "secondPackFifthBenefit", required: false, widget: "string"}
                ]
            }
            ]
        - label: "Tercer paquete"
          name: "thirdPackage"
          identifier_field: "thirdPackage"
          widget: "object"
          fields:
            [
            { label: "Título del paquete", name: "thirdPackageTitle", widget: "string"},
            { label: "Precio del paquete", name: "thirdPackagePrice", widget: "string"},
            { label: "Beneficios del paquete",
              name: "thirdPackageBenefits",
              widget: "object",
              fields:
                [
                { label: "Primer beneficio", label: "thirdPackFirstBenefit", widget: "string"},
                { label: "Segundo beneficio", label: "thirdPackSecondBenefit", required: false, widget: "string"},
                { label: "Tercer beneficio", label: "thirdPackThirdBenefit", required: false, widget: "string"},
                { label: "Cuarto beneficio", label: "thirdPackFourthBenefit", required: false, widget: "string"},
                { label: "Quinto beneficio", label: "thirdPackFifthBenefit", required: false, widget: "string"}
                ]
            }
            ]